// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjGoTNJq3kjRlEiHWZrMUxG7oVCpg1_o',
    appId: '1:968754784411:web:614daf4c540fb785c4fe3e',
    messagingSenderId: '968754784411',
    projectId: 'steam-club-app',
    authDomain: 'steam-club-app.firebaseapp.com',
    storageBucket: 'steam-club-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9neGwt7RqcYKTpXlzUoXJYpJgbPLgMtg',
    appId: '1:968754784411:android:5b2af43e46e87644c4fe3e',
    messagingSenderId: '968754784411',
    projectId: 'steam-club-app',
    storageBucket: 'steam-club-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJJcO9B5fFlg36314Z3Zq3_AJWYSEWV8',
    appId: '1:968754784411:ios:67757e0a767b081ac4fe3e',
    messagingSenderId: '968754784411',
    projectId: 'steam-club-app',
    storageBucket: 'steam-club-app.firebasestorage.app',
    iosBundleId: 'com.steamclub.steamApp',
  );
}
